### ISSUE TITLE
 Error 1146: Table 'campus-recruiting.dictionary' doesn't exist

### ISSUE THREAD

**Issue by lololololkl** [limawanyan/campus-recruiting-api#1]
campus-recruiting-api/internal/repository/mysql/dictionary/gen_dictionary.go:90 Error 1146: Table 'campus-recruiting.dictionary' doesn't exist
[4.011ms] [rows:0] SELECT * FROM `dictionary` WHERE type_code = 'industry_type' AND state = 1 ORDER BY `dictionary`.`id` LIMIT 1

**Comment by limawanyan** [comment]
刚上传了sql脚本，需要执行一下。

**Comment by lololololkl** [comment]
Thank You!
