### ISSUE TITLE
作者大大，能否提供一下后台管理系统？

### ISSUE THREAD

**Issue by lololololkl** [limawanyan/campus-recruiting-api#2]

**Comment by limawanyan** [comment]
无，可以自己实现一个。

**Comment by lololololkl** [comment]
> 无，可以自己实现一个。

需要用来搞毕设。时间紧，加不太明白怎么实现。比如帖子数据库存储的为什么不是纯文字而是HTML？

**Comment by limawanyan** [comment]
可以参考市面上的博客论坛，文章内容都是支持设置格式字体颜色大小添加图片视频等的，html的存储方式称为富文本，解析方式可以参考文章在前台如何显示的。后台管理你可以学习一下go-admin框架，快速生成一个管理后台。

**Comment by lololololkl** [comment]
我有意愿购买该项目配套的后台管理系统，能否添加您的联系方式？

>

**Comment by limawanyan** [comment]
Q：2388962411

**Comment by lololololkl** [comment]
> 
加了好友，麻烦通过一下。
