### ISSUE TITLE
请问后台管理系统有开发吗？

### ISSUE THREAD

**Issue by MouseSun846** [limawanyan/campus-recruiting-api#3]
我看数据表有定义，但是没看到相关代码。
![image](https://github.com/limawanyan/campus-recruiting-api/assets/46400044/0867c4b0-0614-46e4-a1b2-6604dc325643)

**Comment by limawanyan** [comment]
有开发但不完整，采用的goadmin快速开发的，只实现了部分简单的增删改查，您可以尝试自行实现下。
